version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Root@123}
      POSTGRES_DB: ${POSTGRES_DB:-shrishti_dairy}
    ports:
      # If you only want it accessible internally to other docker containers, remove the ports mapping.
      # Exposing to 5432 on server allows external db management tools to connect.
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    ports:
      # Host Port : Container Port
      # Server ka 3050 port nginx use karega proxy ke liye
      - "3050:5555"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  admin_panel:
    build: 
      context: ../admin-panel
    ports:
      - "3051:80"
    depends_on:
      - backend
    restart: always

  # Website frontend
  website:
    build:
      context: ../frontend
    ports:
      - "3060:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
